// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkUwEOQkF0TUJ6TJ57hHXPAcTt2mc2K4Q',
    appId: '1:382617805114:web:f84c969ce1d981bff67003',
    messagingSenderId: '382617805114',
    projectId: 'fruit-2bb6f',
    authDomain: 'fruit-2bb6f.firebaseapp.com',
    storageBucket: 'fruit-2bb6f.appspot.com',
    measurementId: 'G-394819GEND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOMF1HhHl7QmctYRLFXBqfE_qhJi5OXAE',
    appId: '1:382617805114:android:f479c3478068c543f67003',
    messagingSenderId: '382617805114',
    projectId: 'fruit-2bb6f',
    storageBucket: 'fruit-2bb6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO34k-llATFjIDr4qz2CysCoPrjyzW5dQ',
    appId: '1:382617805114:ios:77390432b17c8f3ef67003',
    messagingSenderId: '382617805114',
    projectId: 'fruit-2bb6f',
    storageBucket: 'fruit-2bb6f.appspot.com',
    androidClientId: '382617805114-fmhv2b5c5mhkoqm80frc8agu9gdbkutq.apps.googleusercontent.com',
    iosClientId: '382617805114-um39fsvqe7tbpbil3uvhh7ruuhrou23p.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO34k-llATFjIDr4qz2CysCoPrjyzW5dQ',
    appId: '1:382617805114:ios:77390432b17c8f3ef67003',
    messagingSenderId: '382617805114',
    projectId: 'fruit-2bb6f',
    storageBucket: 'fruit-2bb6f.appspot.com',
    androidClientId: '382617805114-fmhv2b5c5mhkoqm80frc8agu9gdbkutq.apps.googleusercontent.com',
    iosClientId: '382617805114-um39fsvqe7tbpbil3uvhh7ruuhrou23p.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkUwEOQkF0TUJ6TJ57hHXPAcTt2mc2K4Q',
    appId: '1:382617805114:web:14b842a864feeea6f67003',
    messagingSenderId: '382617805114',
    projectId: 'fruit-2bb6f',
    authDomain: 'fruit-2bb6f.firebaseapp.com',
    storageBucket: 'fruit-2bb6f.appspot.com',
    measurementId: 'G-XQS3L8EEYZ',
  );
}
